# Generated by Django 4.0.4 on 2022-08-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='activae',
            field=models.BooleanField(default=False),
        ),
    ]
