# Generated by Django 4.0.4 on 2022-08-29 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_post_activae'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='activae',
            new_name='active',
        ),
    ]
